# Generated by Django 5.0.6 on 2024-08-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.CharField(max_length=500)),
                ('answer_text', models.CharField(max_length=100)),
                ('sug_date', models.DateTimeField(verbose_name='date suggested')),
            ],
        ),
    ]
