# Generated by Django 5.0.6 on 2024-08-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='sug_date',
            new_name='suggested_date',
        ),
        migrations.AddField(
            model_name='question',
            name='suggested',
            field=models.BooleanField(default=False),
        ),
    ]
