# Generated by Django 5.1.1 on 2024-10-28 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_rename_pub_date_question_published_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='published_date',
        ),
        migrations.AddField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 15, 10, 2, 728722), verbose_name='date created'),
        ),
    ]
