# Generated by Django 5.1.1 on 2024-10-28 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_remove_question_published_date_question_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 15, 15, 51, 458003), verbose_name='date created'),
        ),
    ]
