# Generated by Django 5.1.1 on 2024-10-28 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_delete_suggestion_alter_question_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 15, 16, 25, 173708), verbose_name='date created'),
        ),
    ]
